ansible_connection: ssh
ansible_become: true
system_timezone: "Asia/Jerusalem"

ansible_user: ansible
ansible_ssh_private_key_file: "{{ inventory_dir }}/keys/{{ inventory_hostname }}-ansible-bootstrap"
