proxmox_api:
    cluster_name: ENC[AES256_GCM,data:UPgACDv33iyNPQ==,iv:Mqdj4wM2Cts4DYqV3vhXld9WvGLBMxcjN+oqsNO0Jc0=,tag:Jw0QP0PaueLwwToIBBK4vA==,type:str]
    tokens:
        ansible:
            token_id: ENC[AES256_GCM,data:E3ekGd0SUg==,iv:462KDxyPVGCcDhCDjxNs5e/+OE03JwpIGM7KtRPXt0U=,tag:nlMn00UpRgSspTDS5kIrLw==,type:str]
            token_secret: ENC[AES256_GCM,data:nPO0SF6uB4F1OgR7zQNYk0sDhRPQ6Gc91sMJBjYAvkH5+1G/,iv:fC2QzqaBjlULJCykwx5X/pfa9YXGiQRn+t6nx+of+Nc=,tag:Kf1PHFb+OA2UGigRUeDHsw==,type:str]
        terraform:
            token_id: ENC[AES256_GCM,data:csIq+hZIc1Tu,iv:qsNirwveP04h4K4bRlfQL+U8t+8mkHwq+OcNdOXahfo=,tag:GizRj69StYX8/6MKia1qcQ==,type:str]
            token_secret: ENC[AES256_GCM,data:/HKWi2Tu6TOWgILpwUXTnUcRLPw3CszHj0DJqjDK5u7gQGfy,iv:a8giviYrLi7UPvA1GAjRd9OUtZoKgRsU2YnY01llvG0=,tag:k599H7ddUGi79FS3QY+zVA==,type:str]
    url: ENC[AES256_GCM,data:kCcVfDxF6EoZ1TZVu5sTn5Qmj35n0s139vnHuUJ9wfVviuD/Hg==,iv:71QhegfzlpzsVD/sFwwv5pl2AgyQ8x+7o0tg0WIbe0c=,tag:ttIoAKZIxU4oX1en5UPcfg==,type:str]
    user: ENC[AES256_GCM,data:FJCuT0MyCja/ig==,iv:ykikTcQyX4NUkJRNpr/Gh6eeYrx4h02NNvQTiobeZI4=,tag:K8urilWigBmtvOAga7Uohw==,type:str]
sops:
    age:
        - recipient: age1tqhac0nqrat33e7dck3rawlqv6zhxmp9wyeh24y7xjgtcq7hsems8cweyz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaXV2RmJoUjJKWnhJa2dD
            RlBaMUxJWEF2ZUVGOUM5SzhEZkJQa25YV0VZClRxRmJvWWh0bjZRTDhtZDVqeDBC
            RmNtUFd0bzhFbnVyeVRxZEUrOEdDTjQKLS0tIEhvUkhVWjJFTmJ2KzMwblVHSWRH
            a2pWKzJ4cDFRRVpUQnMzeTFFUWdxYjgKbb5izHuv1oSrHUX2gkR9jG8rAjgmuciu
            sSYtLf4e5C/kDR1AelluY3ECrNuDIWdj8SN4lT1tjoHxzxmI15Z32g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T17:04:32Z"
    mac: ENC[AES256_GCM,data:SNSvUMRkBxJttl/RFTDsy0l2FdtTZMF7OVQv21VFSnbCU8wlczFC8SQx6CG2arlCnnHgrLerz+zC6k/gCEv4qSPl6sKLTih7SbBJy1z4Q3lmG64HTWHsUJ0gRYHjt/SXAr/h6xy1StNImFEJL8diJl8KtedetojZLZvnvoe6Pio=,iv:witiKS9qv3d3Opqm9aDTEYMgAVEM1T8nCXqR4nQfEOo=,tag:WXyZAGN+qpWVeF5jsd9QTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
