all:
  children:
    cluster-pve:
      hosts:
        pve1:
          ansible_host: 192.168.51.11
        pve2:
          ansible_host: 192.168.51.12
        pve3:
          ansible_host: 192.168.51.13
        pve4:
          ansible_host: 192.168.51.14

    pbs:
      hosts:
        pbs1:
          ansible_host: 192.168.51.21

    router-pve:
      hosts:
        router1:
          ansible_host: 192.168.51.37
