all:
  children:
    pve_nodes:
      hosts:
        pve1:
          ansible_host: 192.168.51.11
        pve2:
          ansible_host: 192.168.51.12
        pve3:
          ansible_host: 192.168.51.13
        pve4:
          ansible_host: 192.168.51.14

    pbs_nodes:
      hosts:
        pbs1:
          ansible_host: 192.168.51.21

    router_nodes:
      hosts:
        router1:
          ansible_host: 192.168.51.37

    other_linux:
      hosts:
        node1:
          ansible_host: 192.168.51.31

