root_password: ENC[AES256_GCM,data:lGHBJoleTSYKSBS9am72TlsLdgOicNNi,iv:zM68ci5lvjDl44Bt4UXU7NCFagt21KPLBhL45Frexz8=,tag:U0LyKTpGxjdpy8ibM72OxQ==,type:str]
ssh_keys:
    ansible:
        private: ENC[AES256_GCM,data:WvHlCvkbhfZxmICPg7a2UpREdu31nBporc6tmkkmgTcHOApwiFVk5/b+m43rjxZzKIWOpYM0FAjYea5w0Ecn5jY28YQ2qj3snTR0B5AJ2jvQ8D8uWZP3YyiuKiThUxT9tgiJLaqVhe0Qejp4pu3CVmwcI4yEFbA3D3TIA0IbPjiELK7/jw4S5IJMtfkdtzYygsdOdG3C1C6r0BzRIWjwJP0YU8J8xYq599utoohumpedrwj/lS2/n7Uh4fjdrLCIrgBkBD1Rkc0latjd/jiZyWwSUk6ca+OYy6yMK0QUfKAqie9lv7ZCyjmpo5eCXGwTCwuorIhusrdX7YCqRvcxCLr2E2nmVJ8e6Ys44hBYJnRttIjA/U+UAfHhQM7D0DE79i+4YRC8tRnQxeDGyM76gV0uF2ZlHLvy+X+RnhB3OVLACSCUhJu86YaVfqqFGmXNGcwN/AX/rRfQyEZJj4LAjuDZVgnZKvPwvbJbnT/w3l3Q3+qXhrkaQ75ZhwsBj7ne6aU=,iv:spREaT2vDczKYnkZiQEh4Cy7ZMY1RyHEREr18++EfX0=,tag:V+1MFG/ZFOgfTDdaMFxQMg==,type:str]
        public: ENC[AES256_GCM,data:NYkTw0ZN4ZcIdm0UPdkIxrfmdGGtCcPc5TamzNs/N3MA3P8rmLGCLAXi5l5Jdnm9w7zsCkyxggRlv35qNR3kWYwvza74BDk9HAyoef2Jxpw=,iv:W60LH76FpEfoaV+hTugjmc0ynp8OoxXLIaX5Jgw9DVw=,tag:Mep6aBCqJNg9Kb64tB/N/w==,type:str]
sops:
    age:
        - recipient: age1tqhac0nqrat33e7dck3rawlqv6zhxmp9wyeh24y7xjgtcq7hsems8cweyz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUWNnaWdjNHZnMUx1SjhB
            Q01ZRzhPRkJ2U2IvMUdCckMrcldiNXA5QXhnCmRBZjAzdk9mTGpPdEtMeVJvekZN
            RGNzQWVqWnZrUzVQTmN3U1NaQ0NXc3cKLS0tIGpTR2p0V2tNSndTYVF6TXprTEFI
            L2tUeGY5Qm9xOG9TN3p3Si93UnlEWTAKcsYgoCyIMRpIVcqE1P/TNGEZqd43HwQJ
            ChcxUMCk6FlrB13ot6L6S12TIGN/QjzQCf8BJaMzM+uTasZiJ+3Tyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T11:07:36Z"
    mac: ENC[AES256_GCM,data:xgs9vX0qYwCiBo+XQvxQ06TyhcmeFZs66tnsfUl6rrSh3s7ud69MGvmqFyfNYMmyfPfYlJkc5pG0STLcmAO7JPXtQ037TxEffhzgrNQe/DvJeqzkX1bNhw5wFiXbjCJlSFm8yB6Bm9VDlHQer06ZS4oX/+iUlix5QgzmOao2dTw=,iv:+hIqVmq6uCeXhifGlOvJgUfrkS6KNnC02qSmVFbjK94=,tag:9yLSbAGoBtruMNxyC01Smw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
