root_password: ENC[AES256_GCM,data:M03/wuVl9+Ou2D7z73o1Cz4LQdQnaMq6,iv:ms60o4p7UcaFLafFsIEK7NPw7gg9pOIdsFzVYAPV//M=,tag:eiP3GhQ/Wakal/ERVTJ9jA==,type:str]
ssh_keys:
    ansible:
        private: ENC[AES256_GCM,data:awXwHp2X4KFhDeTD+jVu6+wypoMM2l5Lx8Xszp71uvEJVHWCY+gPqTGiTbVXIzYIdSINscFVGiEt/sFl96e5Fxvvf6dH39Px8gG1ahCmEw5V5W+VrhyZ6C3VqEDZhKT6WRXUabgvDHJxNskC8U5sxD8MLWBD78XmNAZ+t+9bHGVt9JlMTJ8AgGgxGN13YL9MwXi+V2Q/k0vc+kRUryn5HAEMJFK/HySgIT0twpSb3rbdAiTU95au7Ap2pY1aYyPdXBTSJ8O3ln7dqjh1IJkK3Ita1DJJn/VaZOa5iFl+Vve0GYO7b8GIQKzVMu+xcsGP6dEf579ynNn2amfhJN7IiRKpHE7kjq577u7rW+VcnQ53ckinZBnNfLpzpDxrfOI2grB+QCVCQGB+TdwR116pgwbNUhRghJ7UUsmEtpNmKCLTu3JgPNH5WQvErEy+twshtjBGbbZ1XY8p8dmQ1GpCu1IBqF7MCXNjvOsv4KM5KbpAnzVjWqUnt6V/5yRJnQ931i8=,iv:BoNpfp1+dG5gFIV6lW0VIRiako7D3uEl3vhqGqkhXyU=,tag:dq7oZoDsMLC8tlrWQburGw==,type:str]
        public: ENC[AES256_GCM,data:N8a8IG6glylh38NSc9NVjJWQ6X3KQ+iiq3UrMi8nMo2mKcpfV4cA+Ww/7VDDQhwEaGzcvB+Y65TuaLE2xwMjiEO941Z0/d5C1/fcN8/vHNc=,iv:QNj1qMyKlrAD1ZVq9BgjxQAKTVf5Rmu8wM/AvIol3YY=,tag:uHC8H/yuMDBwrtpWfYw58A==,type:str]
sops:
    age:
        - recipient: age1tqhac0nqrat33e7dck3rawlqv6zhxmp9wyeh24y7xjgtcq7hsems8cweyz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUTRKZlorTjZQVDJiMHk5
            NURGdWJmTmxlOWJjWGtOcFRQenVDWlZ4a1MwCng0R1BGNXFyMERTRGVjdDFvMkFK
            OGx5aUZpREt3NG9adVVwYURaSHVqNmsKLS0tIEh3TldZY1JwdzloR3UwQ21DdCsr
            SVpLaER6c1Y4TDZyMGRpaHFCS1hONWMKiNeXock+24RAQDx7lyV4GpbeE9l9GiHT
            zJXWQSE1UGeqJ1yFB8nGSP/IAmAkCE+yqS+oPeRzKRvzzFdvxUcVcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T09:22:53Z"
    mac: ENC[AES256_GCM,data:agSxNILNKywdPtksn+K1ba8WGZjs4Wbupmu3BicWq+cf87n5SuKCz8w3zXWUpoDm7wHJTTQWC2GG5Qm7e/NtGeM383rSN6O0sFn9/BGLTEe1R6+c9Wf5cP8n883U9ZPnh/a73VPXFsY/jBHKy/4b5XclJwkcTXZ1SWiT3Lse1tM=,iv:FHhwvl89/wZ65amCdFX0X/LnV3+XvTWBS7A0afNnc0g=,tag:kyb5ZVrehjhDTylPtZeLxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
