---
- name: Prepare OpenWRT template on router Proxmox node
  hosts: router-pve
  become: true
  collections:
    - community.proxmox

  vars:
    proxmox_cluster_name: "router-pve"

  roles:
    - role: proxmox_openwrt_template