---
- import_tasks: hostname.yml
- import_tasks: packages.yml
- import_tasks: locale.yml
- import_tasks: time.yml
- import_tasks: journald.yml
- import_tasks: unattended.yml
  when: enable_unattended_upgrades | default(false)
